apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskboard-chart.fullname" . }}
  labels:
    {{- include "taskboard-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "taskboard-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
