apiVersion: v1
kind: Service
metadata:
  name: monitoring-demo
  namespace: session20-observability
  labels:
    app.kubernetes.io/name: monitoring-demo
spec:
  selector:
    app.kubernetes.io/name: monitoring-demo
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
