apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskboard.fullname" . }}
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "taskboard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "taskboard.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: taskboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "taskboard.fullname" . }}-config
            - secretRef:
                name: {{ include "taskboard.fullname" . }}-secret
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: runtime-tmp
              mountPath: /tmp
            {{- if .Values.persistence.enabled }}
            - name: task-data
              mountPath: /data
            {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: runtime-tmp
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: task-data
          persistentVolumeClaim:
            claimName: {{ include "taskboard.fullname" . }}-data
        {{- end }}
