apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskboard.fullname" . }}-secret
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ toYaml .Values.secret | nindent 2 }}
