apiVersion: v1
kind: Pod
metadata:
  name: web-check
  labels:
    app: web-check
    lab: workload-basics
spec:
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - name: http
          containerPort: 80
