apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: catalog-rs
  labels:
    app: catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog-web
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
